airport: airport.c airport.h explosivecheck.o primecheck.o liquidcheck.o timecheck.o getrandom.o validatevisa.o validatepassport.o
	gcc -o airport -c airport.c explosivecheck.o primecheck.o liquidcheck.o timecheck.o getrandom.o validatevisa.o validatepassport.o
	
explosivecheck.o: explosivecheck.c
	gcc -c explosivecheck.c

timecheck.o: timecheck.c
	gcc -c timecheck.c	
	
primecheck.o: primecheck.c
	gcc -c primecheck.c
	
liquidcheck.o: liquidcheck.c
	gcc -c liquidcheck.c
	
getrandom.o: getrandom.c
	gcc -c getrandom.c
	
validatevisa.o: validatevisa.c
	gcc -c validatevisa.c
	
validatepassport.o: validatepassport.c
	gcc -c validatepassport.c
